import type { OAOperation, OASchema } from './openapi-types.js'

export function generateAfterResponseScripts(operation: OAOperation): Record<string, string> {
  const responses = operation.responses
  if (!responses) return {}

  const result: Record<string, string> = {}
  for (const [code, response] of Object.entries(responses)) {
    const numCode = parseInt(code)
    if (isNaN(numCode)) continue // skip 'default' etc.

    const schema = response.content?.['application/json']?.schema
    const strippedSchema = schema ? stripSchema(schema) : null
    result[code] = buildScriptForStatus(numCode, strippedSchema)
  }
  return result
}

function buildScriptForStatus(expectedCode: number, schema: OASchema | null): string {
  const lines: string[] = [
    '// Generated by openapi2insomnia — response validation script',
    'const status = insomnia.response.code;',
    '',
    `insomnia.test('Status is ${expectedCode}', () => {`,
    `  insomnia.expect(status).to.equal(${expectedCode});`,
    '});',
  ]

  if (schema) {
    lines.push(
      '',
      `const validate = new Function(insomnia.environment.get('__validate__'))();`,
      `const schema = ${JSON.stringify(schema, null, 2)};`,
      `insomnia.test('Status ${expectedCode}: response matches schema', () => {`,
      `  insomnia.expect(status).to.equal(${expectedCode});`,
      '  const body = insomnia.response.json();',
      '  const result = validate(body, schema);',
      `  insomnia.expect(result.valid, result.error ?? 'schema validation failed').to.equal(true);`,
      '});',
    )
  }

  return lines.join('\n')
}

export const VALIDATOR_FN = `\
function validate(data, schema) {
  if (!schema) return { valid: true };

  if (schema.enum) {
    return schema.enum.includes(data)
      ? { valid: true }
      : { valid: false, error: \`expected one of \${JSON.stringify(schema.enum)}, got \${JSON.stringify(data)}\` };
  }

  if (schema.allOf) {
    for (const sub of schema.allOf) {
      const r = validate(data, sub);
      if (!r.valid) return r;
    }
    return { valid: true };
  }

  if (schema.oneOf || schema.anyOf) {
    const options = schema.oneOf ?? schema.anyOf;
    const passed = options.some((sub) => validate(data, sub).valid);
    return passed ? { valid: true } : { valid: false, error: 'no schema matched oneOf/anyOf' };
  }

  if (schema.type === 'object' || schema.properties) {
    if (typeof data !== 'object' || data === null || Array.isArray(data)) {
      return { valid: false, error: \`expected object, got \${Array.isArray(data) ? 'array' : typeof data}\` };
    }
    for (const req of schema.required ?? []) {
      if (!(req in data)) return { valid: false, error: \`missing required field: "\${req}"\` };
    }
    for (const [key, propSchema] of Object.entries(schema.properties ?? {})) {
      if (key in data) {
        const r = validate(data[key], propSchema);
        if (!r.valid) return { valid: false, error: \`"\${key}": \${r.error}\` };
      }
    }
    return { valid: true };
  }

  if (schema.type === 'array') {
    if (!Array.isArray(data)) return { valid: false, error: \`expected array, got \${typeof data}\` };
    for (let i = 0; i < data.length; i++) {
      const r = validate(data[i], schema.items ?? {});
      if (!r.valid) return { valid: false, error: \`[\${i}]: \${r.error}\` };
    }
    return { valid: true };
  }

  if (schema.type === 'string' && typeof data !== 'string')
    return { valid: false, error: \`expected string, got \${typeof data}\` };
  if (schema.type === 'integer' && !Number.isInteger(data))
    return { valid: false, error: \`expected integer, got \${typeof data}\` };
  if (schema.type === 'number' && typeof data !== 'number')
    return { valid: false, error: \`expected number, got \${typeof data}\` };
  if (schema.type === 'boolean' && typeof data !== 'boolean')
    return { valid: false, error: \`expected boolean, got \${typeof data}\` };

  return { valid: true };
}`

// Keeps only validation-relevant fields, capped at depth 8 to avoid huge scripts.
function stripSchema(schema: OASchema, depth = 0): OASchema {
  if (depth > 8) return {}

  const s: OASchema = {}
  if (schema.type) s.type = schema.type
  if (schema.enum) s.enum = schema.enum
  if (schema.required) s.required = schema.required

  if (schema.properties) {
    s.properties = {}
    for (const [k, v] of Object.entries(schema.properties)) {
      s.properties[k] = stripSchema(v, depth + 1)
    }
  }

  if (schema.items) s.items = stripSchema(schema.items, depth + 1)
  if (schema.allOf) s.allOf = schema.allOf.map((sub) => stripSchema(sub, depth + 1))
  if (schema.oneOf) s.oneOf = schema.oneOf.map((sub) => stripSchema(sub, depth + 1))
  if (schema.anyOf) s.anyOf = schema.anyOf.map((sub) => stripSchema(sub, depth + 1))

  return s
}
